# Generated by Django 6.0.3 on 2026-05-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='questions_count',
            field=models.IntegerField(default=0),
        ),
    ]
