# Generated by Django 6.0.3 on 2026-05-02 10:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_answers_count_alter_question_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['-rating', '-created_at'], name='questions_q_rating_e1138f_idx'),
        ),
    ]
