# Generated by Django 6.0.3 on 2026-05-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_question_questions_q_rating_e1138f_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerlike',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно?'),
        ),
        migrations.AddField(
            model_name='questionlike',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно?'),
        ),
    ]
