# Generated by Django 6.0.3 on 2026-05-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_answerlike_is_active_questionlike_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(max_length=4000, verbose_name='Текст ответа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=4000, verbose_name='Текст вопроса'),
        ),
    ]
