services:
    db:
        image: postgres:18.3-alpine
        container_name: niceanswer_db
        env_file:
            - .env.docker
        volumes:
            - postgres_data:/var/lib/postgresql
        ports:
            - "5432:5432"

    redis:
        image: redis:8-alpine
        container_name: niceanswer_redis
        ports:
            - "6379:6379"
        restart: always

    centrifugo:
        image: centrifugo/centrifugo:v6
        container_name: niceanswer_centrifugo
        volumes:
            - ./centrifugo.json:/centrifugo/config.json
        command: centrifugo -c config.json
        ports:
            - "8001:8000"

    maildev:
        image: maildev/maildev
        container_name: niceanswer_maildev
        ports:
            - "1080:1080"
            - "1025:1025"

    web:
        build: .
        container_name: niceanswer_web
        command: gunicorn -c gunicorn.conf.py
        volumes:
            - .:/app
            - ./media:/app/media
        ports:
          - "8000:8000"
          - "8081:8081"
        env_file:
          - .env.docker
        depends_on:
            - db
            - redis
            - centrifugo
            - maildev

    celery:
        build: .
        container_name: niceanswer_celery
        command: celery -A application worker --loglevel=info
        volumes:
            - .:/app
            - ./media:/app/media
        env_file:
            - .env.docker
        depends_on:
            - db
            - redis
            - centrifugo
            - maildev

    celerybeat:
        build: .
        container_name: niceanswer_celerybeat
        command: celery -A application beat --loglevel=info
        volumes:
            - .:/app
        env_file:
            - .env.docker
        depends_on:
            - db
            - redis

    nginx:
        image: nginx:alpine
        container_name: niceanswer_nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./static:/app/static:ro
            - ./media:/app/media:ro
        depends_on:
            - web

volumes:
    postgres_data:
