# Generated by Django 6.0.3 on 2026-05-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='answers_count',
            field=models.IntegerField(default=0),
        ),
    ]
